#ifndef __PYRO_SENTRY_FUNC_CONFIG_H__
#define __PYRO_SENTRY_FUNC_CONFIG_H__

#define GIMBAL_ID  1
#define CHASSIS_ID 2
#define BOARD_ID   CHASSIS_ID

#define DR16_UART PYRO_UART5
#define REFEREE_UART PYRO_UART10
#define SUPERCAP_UART PYRO_UART7

#endif
